- tset.js
- careted singin page 
- created custom components for button sso we can reuse
> just testing

- config/db.js
- controllers/userController.js
- models/user.js
- package-lock.json
- package.json
- routes/userRoutes.js
- server.js
- tset.js
- signup
- sign in
- authentication based on role
> registration and authentication

- controllers/profileController.js
- controllers/userController.js
- models/profile.js
- models/user.js
- routes/profileRoutes.js
- routes/userRoutes.js
- server.js
- user model updated
- signup controller updated
> signup and login

- controllers/testReportController.js
- models/testReport.js
- routes/testReportRoutes.js
- Test Report model updated with patientId
- Test Report controller updated with get report by patientId
- Test Report routes updated with get report by patientId
> Test report model, controller and routes updated with patientId

- controllers/profileController.js
- models/profile.js
- Profile Model update with PatientId
- Profile Controller update profile and get profile update with patientId
> Profile updated with patientId

- controllers/userController.js
- in login controller role also returned along with token
> User Controller changes

- controllers/profileController.js
- controllers/userController.js
- models/profile.js
- profile model updated with default values
- user controller updated with profile creation
> Profile and User controller 

- controllers/userController.js
- models/profile.js
- from profile model remove default values
- from user controller updated profile save
> Profile Model and User Controller

- controllers/profileController.js
- controllers/userController.js
- models/profile.js
- Profile model updated
- profile controller get and update profile updated
> Profile and user controller update

- controllers/profileController.js
- Profile controller get profile details updated
> Profile controllers updated

- controllers/profileController.js
- profile controller updated for get profile details
> profile controller updated 

- controllers/bookAppointmentController.js
- controllers/doctorListController.js
- controllers/medicalHistoryController.js
- controllers/photoUploadController.js
- models/appointment.js
- models/doctorList.js
- routes/bookAppointmentRoutes.js
- routes/doctorListRoutes.js
- routes/medicalHistoryRoutes.js
- routes/profileRoutes.js
- server.js
-### Profile controller updated
- server file updated with all routes
> Profile controller

- controllers/profileController.js
- models/profile.js
- profile model profilePhoto type change
- profile controller profilePhoto type change
> Profile controller and model update

- controllers/bookAppointmentController.js
- routes/bookAppointmentRoutes.js
- Appointment list controller update with get appointment list by patientId
- - Appointment list routes update with get appointment list by patientId
> Appointment List Update

- controllers/doctorListController.js
> Doctor list controller

- models/doctorList.js
> Doctor list model and controller update

- controllers/bookAppointmentController.js
- models/appointment.js
- routes/bookAppointmentRoutes.js
-  appointment model updated with doctorId ref with DoctorList
- book appointment controller and get appointment by doctorId updated
- book appointment routes updated
> Book Appointments Controller, Model, Routes updated

- controllers/doctorListController.js
- models/doctorList.js
- routes/doctorListRoutes.js
- Doctor list model updated with doctorId
- Doctor list controller addDoctor controller updated
- Doctor list routes updated
> doctor list controller, model, routes updated

- models/user.js
> user model updated

- routes/bookAppointmentRoutes.js
> appointment routes auth updated

- controllers/bookAppointmentController.js
- controllers/medicalHistoryController.js
- controllers/profileController.js
- controllers/userController.js
- models/appointment.js
- models/profile.js
- models/user.js
- Users model controller updated with patientId
- From profile model, controller deleted patientId
- Book appointment and medical history patientId ref change from model and controller
> Users, profile, book appointment, medical history updated

- controllers/doctorListController.js
- models/doctorList.js
> Doctor list controller and model updated

- models/payment.js
- routes.rest
- routes/paymentRoutes.js
> payments routes and models updated

- models/payment.js
- routes/paymentRoutes.js
- server.js
> payments model routes and server file updated
